local core = require("config.core")

core.packadd({
  core.gh("nvim-mini/mini.nvim"),
  core.gh("catppuccin/nvim"),
  core.gh("rachartier/tiny-inline-diagnostic.nvim"),
  {
    core.gh("nvim-neo-tree/neo-tree.nvim"),
    core.gh("nvim-lua/plenary.nvim"),
    core.gh("MunifTanjim/nui.nvim"),
    core.gh("nvim-tree/nvim-web-devicons"),
  },
  core.gh("nvimdev/dashboard-nvim"),
  core.gh("folke/which-key.nvim"),
  core.gh("nvim-lualine/lualine.nvim"),
  core.gh("akinsho/bufferline.nvim"),
  core.gh("lukas-reineke/indent-blankline.nvim"),
  {
    core.gh("nvim-telescope/telescope.nvim"),
    core.gh("nvim-lua/plenary.nvim"),
  },
  {
    core.gh("folke/noice.nvim"),
    core.gh("MunifTanjim/nui.nvim"),
    core.gh("rcarriga/nvim-notify"),
  },
  core.gh("aznhe21/actions-preview.nvim"),
  core.gh("mason-org/mason-lspconfig.nvim"),
  core.gh("mason-org/mason.nvim"),
  core.gh("owallb/mason-auto-install.nvim"),
  core.gh("neovim/nvim-lspconfig"),
  {
    core.gh("saghen/blink.cmp"),
    core.gh("rafamadriz/friendly-snippets"),
  },
  core.gh("folke/lazydev.nvim"),
  core.gh("smoka7/hop.nvim"),
})

require("config.ui")
require("config.lsp")
